### ISSUE TITLE
add support for `apply:` in the manifest

### ISSUE THREAD

**Issue by fearthecowboy** [microsoft/cella#110]
- `apply:` allows us to pull files from the artifact folder and insert them into the project. no effect on `ce use` consumption of package
    - Q: possible other names: [apply-changes:,insert:,transform:,modify:,project:]?
    - show warnings if the files exist and are not the same as the source file? (would happen if the files are there from a previous activation and modified.)
    - 
    ``` yaml
      # the 'apply' section copies files from the artifact folder to the project folder.
      # apply:
      #  <KIND>:  ## [c/header/assembler/linker/etc] -- the kind may let us update/modify project files in the longer term
      #    <TARGET-PATH>: <SOURCE-PATH>
      #      -- TARGET-PATH is relative to the folder containing environment.yaml 
      #      -- SOURCE-PATH is relative to the artifact folder after being unpacked.


      apply:  # this section copies files 
        
        # target: source
        c: 
          src/board/main.c: project_template/board.c   
          src/board/main.cpp: project_template/board.cpp

        header: 
          src/include/board.h: project_template/board.h
        
        assembler: 
          src/asm/startup.s: Device/ARM/ARMCM3/Source/IAR/startup_ARMCM3.s

        linker: 
          src/linker/gcc_arm.ld: Device/ARM/ARMCM3/Source/GCC/gcc_arm.ld

        misc:
          docs/ : project_template/docs/** # support copying with wildcard/globbing

    NOT exists:src/board.c:  # maybe we should have a mediaquery for 'exists'? - then we could have an apply section active only when a file doesn't exist in the project.
      apply:


      ```
